// Renders every non-TS config surface from the single source of truth
// (src/shared-config.ts). Run via `pnpm config:render` (which builds first).
//
//   node dist/render-config.js            # write changed files
//   node dist/render-config.js --check    # exit nonzero if anything is stale (CI)
//   node dist/render-config.js --print    # print rendered content, write nothing
//
// The MCP launchers (.mcp.json, .codex/config.toml) are produced by reusing
// configureHost from host-config.ts (atomic writes, backups, path safety); the
// remaining surfaces are deterministic strings emitted here.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { configureHost, type HostName } from "./host-config.js";
import {
  BACKENDS,
  baseUrl,
  clusterModels,
  CLUSTER_CLEANUP_MODELS,
  llmCliModels,
  MODELS,
  opencodeDefault,
  opencodeModels,
  type OpencodeProvider,
  roleAlias,
} from "./shared-config.js";

type Mode = "write" | "check" | "print";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const GENERATED_LINE =
  "GENERATED by `pnpm config:render` — edit src/shared-config.ts, not this file.";
const hashNotice = `# ${GENERATED_LINE}`;

// --- surface renderers ------------------------------------------------------

function renderOpencodeJson(): string {
  const provider = (
    key: OpencodeProvider,
    name: string,
    backend: "controller" | "cluster",
    apiKey: string,
    extraOptions: Record<string, unknown> = {},
  ): Record<string, unknown> => {
    const models: Record<string, { name: string }> = {};
    for (const model of opencodeModels(key)) models[model.id] = { name: model.name };
    return {
      npm: "@ai-sdk/openai-compatible",
      name,
      options: { baseURL: baseUrl(backend), apiKey, ...extraOptions },
      models,
    };
  };
  const defaultModel = opencodeDefault("omlx");
  const config = {
    $schema: "https://opencode.ai/config.json",
    provider: {
      omlx: provider("omlx", "oMLX (local MLX)", "controller", "omlx-local"),
      mlxcluster: provider("mlxcluster", "MLX Cluster (M5 + M4)", "cluster", "local-mlx-cluster", {
        timeout: 600_000,
      }),
    },
    ...(defaultModel ? { model: `omlx/${defaultModel}` } : {}),
    permission: {
      websearch: "allow",
      webfetch: "allow",
    },
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

function renderExtraOpenaiModelsYaml(): string {
  const lines = [
    hashNotice,
    "#",
    "# Deploy to: ~/Library/Application Support/io.datasette.llm/extra-openai-models.yaml",
    "# Tells the `llm` CLI how to reach the models served on the controller endpoint.",
  ];
  const apiBase = baseUrl("controller");
  for (const { alias, modelId } of llmCliModels()) {
    lines.push(
      `- model_id: ${alias}`,
      `  model_name: ${modelId}`,
      `  api_base: ${apiBase}`,
      `  api_key_name: lmstudio`,
    );
  }
  return `${lines.join("\n")}\n`;
}

function renderShellEnv(): string {
  return (
    [
      hashNotice,
      "# Sourced by shell/llm.zsh.",
      `export LLM_SERVE_PORT=${String(BACKENDS.controller.port)}`,
      `export LLM_MODEL=${roleAlias("daily-driver")}`,
      `export LLM_MODEL_HQ=${roleAlias("daily-hq")}`,
    ].join("\n") + "\n"
  );
}

function renderClusterModelsEnv(): string {
  const { fast, overnight, test } = clusterModels();
  return (
    [
      hashNotice,
      "# Shared model profile defaults, available on both Macs. Values may be",
      "# overridden after sourcing, but both ranks must use the same exact repo.",
      "",
      `CLUSTER_MODEL_FAST="\${CLUSTER_MODEL_FAST:-${fast}}"`,
      `CLUSTER_MODEL_OVERNIGHT="\${CLUSTER_MODEL_OVERNIGHT:-${overnight}}"`,
      `CLUSTER_MODEL_TEST="\${CLUSTER_MODEL_TEST:-${test}}"`,
      "",
      "# Cache repositories removed by the guarded local cleanup task.",
      `CLUSTER_LLAMA_CLEANUP_MODELS="\${CLUSTER_LLAMA_CLEANUP_MODELS:-${CLUSTER_CLEANUP_MODELS.join(" ")}}"`,
    ].join("\n") + "\n"
  );
}

function renderMenubarModelsJson(): string {
  const models = MODELS.map((model) => ({
    id: model.id,
    quality: model.quality,
    backends: model.servedBy,
    contextTokens: model.contextTokens ?? BACKENDS[model.servedBy[0] ?? "controller"].contextTokens,
    llmAlias: model.llmAlias ?? null,
    role: model.role ?? null,
    inference: model.inference ?? null,
  }));
  return `${JSON.stringify({ "//": GENERATED_LINE, models }, null, 2)}\n`;
}

// --- driver -----------------------------------------------------------------

export type Surface = { relativePath: string; content: string };

export function surfaces(): Surface[] {
  return [
    { relativePath: "config/opencode.json", content: renderOpencodeJson() },
    { relativePath: "config/extra-openai-models.yaml", content: renderExtraOpenaiModelsYaml() },
    { relativePath: "shell/llm.env", content: renderShellEnv() },
    { relativePath: "cluster/models.env", content: renderClusterModelsEnv() },
    { relativePath: "menubar/models.json", content: renderMenubarModelsJson() },
  ];
}

// Host launchers reused from the delegate's own idempotent renderer.
const HOST_TARGETS: HostName[] = ["claude", "codex"];

async function readIfPresent(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      (error as { code?: unknown }).code === "ENOENT"
    ) {
      return null;
    }
    throw error;
  }
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const mode: Mode = argv.includes("--check")
    ? "check"
    : argv.includes("--print")
      ? "print"
      : "write";

  let drift = false;

  for (const surface of surfaces()) {
    const target = join(repoRoot, surface.relativePath);
    if (mode === "print") {
      process.stdout.write(`# ---- ${surface.relativePath} ----\n${surface.content}\n`);
      continue;
    }
    const existing = await readIfPresent(target);
    const changed = existing !== surface.content;
    if (mode === "check") {
      if (changed) {
        drift = true;
        console.error(`drift: ${surface.relativePath}`);
      }
      continue;
    }
    if (changed) {
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, surface.content, "utf8");
      console.log(`wrote:     ${surface.relativePath}`);
    } else {
      console.log(`unchanged: ${surface.relativePath}`);
    }
  }

  for (const host of HOST_TARGETS) {
    if (mode === "print") {
      const preview = await configureHost({ host, workspaceRoot: repoRoot, apply: false });
      process.stdout.write(`# ---- ${preview.target_path} ----\n${preview.content}\n`);
      continue;
    }
    if (mode === "check") {
      const preview = await configureHost({ host, workspaceRoot: repoRoot, apply: false });
      if (preview.changed) {
        drift = true;
        console.error(`drift: ${host} launcher (${preview.target_path})`);
      }
      continue;
    }
    const result = await configureHost({ host, workspaceRoot: repoRoot, apply: true });
    console.log(`${result.changed ? "wrote:    " : "unchanged:"} ${host} launcher`);
  }

  if (mode === "check" && drift) {
    console.error("\nConfig is stale. Run `pnpm config:render` and commit the result.");
    process.exit(1);
  }
}

const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
